# Generated by Django 4.1.5 on 2023-09-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConcurentGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Observed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.goods')),
                ('observed_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.observed')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='observed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.observed'),
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.observed')),
            ],
        ),
        migrations.CreateModel(
            name='ConcurentPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.concurentgoods')),
            ],
        ),
        migrations.AddField(
            model_name='concurentgoods',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.observed'),
        ),
        migrations.AddField(
            model_name='concurentgoods',
            name='origin_good_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.goods'),
        ),
    ]
