# Generated by Django 4.1.5 on 2023-09-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcurentGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.observed')),
                ('origin_good_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.goods')),
            ],
        ),
    ]
