# Generated by Django 4.1.5 on 2023-08-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='good_name',
            new_name='good_id',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='observed_name',
            new_name='observed_id',
        ),
        migrations.RenameField(
            model_name='prices',
            old_name='good_name',
            new_name='good_id',
        ),
        migrations.RenameField(
            model_name='prices',
            old_name='observed_name',
            new_name='observed_id',
        ),
    ]
