# Generated by Django 4.1.5 on 2023-09-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_concurentgoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurentgoods',
            name='origin_good_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.goods'),
        ),
    ]
