# Generated by Django 4.1.5 on 2023-08-19 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_rename_good_name_links_good_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
